apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory-container
        image: docker.io/harsh042/inventory-manager:latest
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 5000
